Fix exception when translating ContextVar[] generic in pyi files
This exception happens because only official `typing` classes have the `copy_with` method, like `typing.List`.

```
Traceback (most recent call last):
  File "/home/ubuntu/modal/venv/lib/python3.11/site-packages/synchronicity/type_stubs.py", line 505, in _formatannotation
    annotation.copy_with(
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object '_contextvars.ContextVar' has no attribute 'copy_with'
```